name: Deploy FastAPI to Azure VM

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /path/to/your/app
            git pull origin main
            # Install dependencies if needed
            source venv/bin/activate
            pip install -r requirements.txt
            # Build Docker image
            docker build -t fastapi-app .
            # Run Docker container
            docker run -d -p 8000:8000 --env-file .env fastapi-app
            # Restart the FastAPI app (in case using systemd or other)
            sudo systemctl restart fastapi-app
          EOF

      - name: Verify deployment
        run: |
          curl http://${{ secrets.SSH_HOST }}/api/v1/books/1

