name: Deploy FastAPI to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e  # Stop execution on error

            cd /path/to/your/app || exit 1
            git pull origin main

            # Ensure virtual environment exists and activate
            if [ ! -d "venv" ]; then python3 -m venv venv; fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Stop and remove existing Docker container (if exists)
            docker ps -q --filter "name=fastapi-app" | grep -q . && docker stop fastapi-app && docker rm fastapi-app

            # Build and run Docker container
            docker build -t fastapi-app .
            docker run -d --name fastapi-app -p 8000:8000 --env-file .env fastapi-app

            # Restart FastAPI app (if using systemd)
            sudo systemctl restart fastapi-app || true
          EOF

      - name: Verify deployment
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.SSH_HOST }}:8000/api/v1/books/1)
          if [[ "$RESPONSE" -ne 200 ]]; then exit 1; fi

