name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy application
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r * user@your-server:/path/to/your/app

      - name: Restart application
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server "cd /path/to/your/app && pm2 restart app_name"

