name: Deploy to production environment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /root/fastapi-book-project
            git fetch origin main
            git reset --hard origin/main
            pip install -r requirements.txt
            sudo systemctl restart fastapi
