name: Deploy FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH for AWS deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: SSH into the AWS server and deploy
        run: |
          echo "Starting deployment process on AWS server"
          
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_PUBLIC_IP }} << 'EOF'
            
            cd /path/to/your/fastapi/project
            git pull origin main
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi-app
            sudo systemctl restart nginx

            echo "Deployment complete!"

          EOF

